---
language: generic
services:
  - docker

after_success:
  make docker-push

before_script:
  # Setup dependency management tool
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin quay.io

script:
  - make docker-build test